"""Adds webauthn_credentials

Revision ID: 72cb90f736e4
Revises: 5c1a59daaa47
Create Date: 2025-09-28 00:39:01.888746

"""
from alembic import op
import sqlalchemy as sa
import flask_security

# revision identifiers, used by Alembic.
revision = '72cb90f736e4'
down_revision = '5c1a59daaa47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(length=1024), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', flask_security.datastore.AsaList(), nullable=True),
    sa.Column('backup_state', sa.Boolean(), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('extensions', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastuse_datetime', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('usage', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webauthn_credentials_credential_id'), ['credential_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webauthn_credentials_credential_id'))

    op.drop_table('webauthn_credentials')
    # ### end Alembic commands ###
