"""Adds product table

Revision ID: 80014026a880
Revises: 72cb90f736e4
Create Date: 2025-09-29 10:20:25.162985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80014026a880'
down_revision = '72cb90f736e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
